# Python Basics

Welcome to your first sesson. This session gives you a brief introduction to Python. 

**Instructions:**
- You will be using Python 3.
- Focusing on Data types and structures using Numpy and Pandas
- After coding of every line, press control enter 

**After this assignment you will:**
- Be able to use jupyter notebook
- Be able to use numpy functions and numpy matrix/vector operations
- Understand the concept of "broadcasting"
- Be able to vectorize code

Let's dive into Python!

In [3]:
i = 100
print(type(i))


a = "rims"
print(type(a))


i_dec = 10.12345
print(type(i_dec))


n=[2,33,4,39,17,89,100,125] 

<class 'int'>
<class 'str'>
<class 'float'>


In [4]:
### Slicing in list
n[4]=50
print(n)
n[3:6]


[2, 33, 4, 39, 50, 89, 100, 125]


[39, 50, 89]

In [5]:
isinstance(n, list)

True

- Tuple is an ordered sequence of items same as a list. 
- The only difference is that tuples are immutable. Tuples once created cannot be modified.

In [6]:
tup = (2,6,'infosys','2020-12-25')
tup

(2, 6, 'infosys', '2020-12-25')

In [7]:
tup[3]


'2020-12-25'

- SET
- Set is an unordered collection of unique items. 
- Set is defined by values separated by comma inside braces { }.
- Items in a set are not ordered.

In [8]:

b = {5,2,3,1,4}

# printing set variable
print("B = ", b)

B =  {1, 2, 3, 4, 5}


- Dictionary is an unordered collection of key-value pairs.
- dictionaries are defined within braces {} with each item being a pair in the form key:value. 
- Key and value can be of any type.

In [10]:
dict = {'stock': 'pvr', 'price': 1435, 'Class': 'Mid'}
print(dict)

{'stock': 'pvr', 'price': 1435, 'Class': 'Mid'}


In [11]:
dict1 = dict.copy()
print(dict1)
dict2 = {'exchange': 'NSE' }
print(dict2)
dict1.update(dict2)
print(dict1)

{'stock': 'pvr', 'price': 1435, 'Class': 'Mid'}
{'exchange': 'NSE'}
{'stock': 'pvr', 'price': 1435, 'Class': 'Mid', 'exchange': 'NSE'}


In [14]:
stddata = {
            "Name":['x','y',"z","u"],
            "price":[2309,1975,2000,1456],
            "signal":[-1,1,1,-1]
          }
stddata
type(stddata)

dict

In [15]:
str1 = "this is string example....wow!!!"
str2 = "exam";
print(str1)
print(len(str1))  #len is lenth
type(str1)

this is string example....wow!!!
32


str

In [16]:
str = "this is string example....wow!!! this is really string"
print (str.replace("is", "was")) #(actual,replaced)
print (str.replace("is", "was", 3))

thwas was string example....wow!!! thwas was really string
thwas was string example....wow!!! thwas is really string


In [17]:
import time
print (time.localtime())

time.struct_time(tm_year=2023, tm_mon=8, tm_mday=6, tm_hour=22, tm_min=17, tm_sec=20, tm_wday=6, tm_yday=218, tm_isdst=0)


In [18]:
localtime = time.asctime( time.localtime(time.time()) )
print ("Local current time :", localtime)

Local current time : Sun Aug  6 22:17:25 2023


In [19]:
import calendar
cal = calendar.month(2023, 8)
print ("Here is the calendar:")
print (cal)

Here is the calendar:
    August 2023
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31



### conditonal statements
- for loop
- If condition
- while 

In [201]:
numbers=[2,33,4,39]
for num in numbers:
    print(num)

2
33
4
39


In [203]:
m=2
n=4
if m>n:
    print(m)
else:
    print(n)

4


In [205]:
numbers=[2,33,4,39,55,74,37,22,23,9,10]
for num in numbers:
  if num%2==0:
    print (num,"\t",num**2)
  elif num%2==1:
    print (num,"\t",num)
  

2 	 4
33 	 33
4 	 16
39 	 39
55 	 55
74 	 5476
37 	 37
22 	 484
23 	 23
9 	 9
10 	 100


In [206]:
a = 21
b = 10
c = 0
c = a + b
print ("Line 1 - Value of c is ", c)
c += a
print ("Line 2 - Value of c is ", c )
c *= a
print ("Line 3 - Value of c is ", c )

Line 1 - Value of c is  31
Line 2 - Value of c is  52
Line 3 - Value of c is  1092


In [209]:
numberString = "01256748983"
val = 0
for char in numberString:
  val +=  len(char)
print(val)

11


In [213]:
count = 4
while (count <10 ):
  print("count is ",count)
  count = count + 1

count is  4
count is  5
count is  6
count is  7
count is  8
count is  9


In [220]:
array = list(range(10,50))
print(array)
type(array)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


list

In [224]:
 var = list(range(0,10))
 for i in var:               
    print("numerics",i)
 letter = "python"
 for i in letter:
   print("letters",i)

numerics 0
numerics 1
numerics 2
numerics 3
numerics 4
numerics 5
numerics 6
numerics 7
numerics 8
numerics 9
letters p
letters y
letters t
letters h
letters o
letters n


In [228]:
for letter in "python":
  if letter == "h":
    break
  print("letter",letter)

letter p
letter y
letter t


### Basics of Numpy and Pandas
- Numpy :arange,linspace,array,
- Series
- Data Frame

In [236]:
import numpy as np # library / package has set of functions - analysis maths,computation speed
import pandas as pd # data structure convert into data frame 
import math

In [249]:
n =  np.arange(0,10,2)
print(n)
print(n.shape)  # spec. no. of rows and col (no. of elements in the Row)
print(n.dtype)

[0 2 4 6 8]
(5,)
int64


In [252]:
h = np.arange(18).reshape(3,2,3) #reshape(3D,2R,3C)
h 

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [255]:
my_array = np.linspace(1,10,20) 
my_array
print(my_array.shape)

(20,)


In [270]:
#np.random.randn (12, 5) # (nrow,ncol)

val = np.random.randn (12, 5)
np.mean(val)  # provides mean/avg
np.std(val)

mean,stdev,variance = np.mean(val),np.std(val),np.var(val)
print("mean:",mean)
print("stdev:",stdev)
print("variance:",variance)

mean: -0.14389043512022004
stdev: 0.8206990451299094
variance: 0.6735469226771451


In [272]:
my_array = np.array([[10,11,12],[20,21,22],[30,32,44]])
my_array
print(my_array.shape) 

(3, 3)


In [278]:
A = np.array([12, 42, 23, 54, 65, 68, 47, 80])
#print (A[2:]) # slicing from 5 positon on wards 
#print (A[:3]) # slicing till 3rd position of elements from the 0th position
#print (A[2:6])
print (A [::3]) #printing alternate from 0th positon

[12 54 47]


In [302]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print('a+b:', a + b) #add
print("a - b  =", a - b)# minus
print("a * b  =", a * b) # product
print("a / b  =", a / b) #div
print("a // b  =", a  // b) #divisibl
print("a % b  =", a % b) # reminder
print("a ** b =", a ** b) # sqr

a+b: [19 27 35 43]
a - b  = [ 9 19 29 39]
a * b  = [70 92 96 82]
a / b  = [ 2.8         5.75       10.66666667 20.5       ]
a // b  = [ 2  5 10 20]
a % b  = [4 3 2 1]
a ** b = [537824 279841  32768   1681]


In [290]:
print(np.log(10))
print(np.exp(2.302585092994046))
print(np.sqrt(10).round(2))

2.302585092994046
10.000000000000002
3.16


In [293]:
import math
import numpy as np
numbers=[2,33,4,39,55,75,37,21,23,4,10]
for num in numbers:
  print ("num:",num,"\t",(np.log(num)))

num: 2 	 0.6931471805599453
num: 33 	 3.4965075614664802
num: 4 	 1.3862943611198906
num: 39 	 3.6635616461296463
num: 55 	 4.007333185232471
num: 75 	 4.31748811353631
num: 37 	 3.6109179126442243
num: 21 	 3.044522437723423
num: 23 	 3.1354942159291497
num: 4 	 1.3862943611198906
num: 10 	 2.302585092994046


In [304]:
m = np.array([21,56,43,78])
m
n = np.array([21,56,42,89])
n == m

array([ True,  True, False, False])

In [316]:
a = np.array([[10.3,9.1,8.5,7.4], [5,8,9,10]])
a

array([[10.3,  9.1,  8.5,  7.4],
       [ 5. ,  8. ,  9. , 10. ]])

In [312]:
signals = ['Buy','Sell','Sell','Buy','Buy','Sell','Buy'] 
print("signals:",signals)
sig =np.repeat(np.array(["Buy","Sell","Hold"]), [5,8,2])
print("sig:",sig)
type(signals)

signals: ['Buy', 'Sell', 'Sell', 'Buy', 'Buy', 'Sell', 'Buy']
sig: ['Buy' 'Buy' 'Buy' 'Buy' 'Buy' 'Sell' 'Sell' 'Sell' 'Sell' 'Sell' 'Sell'
 'Sell' 'Sell' 'Hold' 'Hold']


list

In [318]:
for func in (a.mean,a.std,a.min,a.max):
  print(func.__name__, "=", func())

mean = 8.4125
std = 1.5711759131300354
min = 5.0
max = 10.3


In [321]:
import pandas as pd
series1 =  pd.Series([100, 250, 300, 500])
print(series1)
series2 =  pd.Series([100.1, 250.5, 300.0, 500.23],index = ['I','II','III','K'])
print(series2)

0    100
1    250
2    300
3    500
dtype: int64
I      100.10
II     250.50
III    300.00
K      500.23
dtype: float64


In [326]:
stocks_set1 = ['Alphabet', 'IBM', 'Tesla', 'Infosys']
stocks_set2 = ['Alphabet', 'Facebook', 'Tesla', 'Infosys']
S3 = pd.Series([100, 250, 300, 500], index = stocks_set1)
S4 = pd.Series([500, 700, 110, 700], index = stocks_set2)
print (S3)  
print("\n")
print (S4) 
print("\n")
print(S3+S4)

Alphabet    100
IBM         250
Tesla       300
Infosys     500
dtype: int64


Alphabet    500
Facebook    700
Tesla       110
Infosys     700
dtype: int64


Alphabet     600.0
Facebook       NaN
IBM            NaN
Infosys     1200.0
Tesla        410.0
dtype: float64


In [333]:
my_array = np.array([[10,11,12,16,18],[20,21,22,25,28],[30,32,44,50,60],[40,45,48,50,62]])
print(my_array)
my_array.shape
my_array.dtype

[[10 11 12 16 18]
 [20 21 22 25 28]
 [30 32 44 50 60]
 [40 45 48 50 62]]


dtype('int64')

In [355]:
my_array1 = pd.DataFrame(my_array)

my_array1.columns=["A","B","C","D","E"]
my_array1.index=["I","II","III","IV"]
my_array1
#my_array1.info()  # meta data, data about data, strucutre of data set
#my_array1.describe()

A   B   C   D   E
I    10  11  12  16  18
II   20  21  22  25  28
III  30  32  44  50  60
IV   40  45  48  50  62

In [351]:
print("This is output")
my_array1.describe().round(2).T # to display descriptive stats

This is output


count   mean    std   min    25%   50%    75%   max
A    4.0  25.00  12.91  10.0  17.50  25.0  32.50  40.0
B    4.0  27.25  14.61  11.0  18.50  26.5  35.25  45.0
C    4.0  31.50  17.31  12.0  19.50  33.0  45.00  48.0
D    4.0  35.25  17.42  16.0  22.75  37.5  50.00  50.0
E    4.0  42.00  22.33  18.0  25.50  44.0  60.50  62.0

In [381]:
df = my_array1
df['target_var'] = df.iloc[:,0:3].mean(axis=1)
df
row_wise = df.iloc[0:4,:].sum(axis=0)
print(row_wise)
print(df)
df['D']
#choose object and say target var. name = choose the object and variable. do sum based col wise

A                        100
B                        109
C                        126
D                        141
E                        168
target_var           111.667
hobby         SBISBIHDFCHDFC
bank          SBISBIHDFCHDFC
dtype: object
      A   B   C   D   E  target_var hobby  bank
I    10  11  12  16  18   11.000000   SBI   SBI
II   20  21  22  25  28   21.000000   SBI   SBI
III  30  32  44  50  60   35.333333  HDFC  HDFC
IV   40  45  48  50  62   44.333333  HDFC  HDFC


I      16
II     25
III    50
IV     50
Name: D, dtype: int64

In [112]:
#df['u'] = df.iloc[:,[0,1,3]].sum(axis=1)
#df['z'] = df. loc[:,["A","C","D"]].sum(axis=1)

#df
#df[1:3]
#df[["D","F"]]
#df.iloc[[2,3,0]]
#df.insert(1, "AI", [12, 18, 15])
df


A   B   C   D   E   X  ysum
I    10  11  12  16  18  21   NaN
II   20  21  22  25  28  41   NaN
III  30  32  44  50  60  62   NaN
IV   40  45  48  50  62  85   NaN

In [368]:
#assign can do multiple computation in the data set
df.assign(
    MM = df["D"] / (df["E"] / 100) ** 2,
    PP = df["C"] > 15
)

A   B   C   D   E  target_var          MM     PP
I    10  11  12  16  18   11.000000  493.827160  False
II   20  21  22  25  28   21.000000  318.877551   True
III  30  32  44  50  60   35.333333  138.888889   True
IV   40  45  48  50  62   44.333333  130.072841   True

In [382]:
#df.query("A > 10 or d < 30 ")
#df.query("A > 10 and z >30 ")
#df.sort_index(axis=0,inplace=True)
#df.sort_values(by="D",inplace=True)
#df["dec"] = np.nan
#final_df_clean = df.dropna(axis=1,how="all")
df["bank"] = ["SBI", "SBI", "HDFC", "HDFC"]
df

A   B   C   D   E  target_var hobby  bank
I    10  11  12  16  18   11.000000   SBI   SBI
II   20  21  22  25  28   21.000000   SBI   SBI
III  30  32  44  50  60   35.333333  HDFC  HDFC
IV   40  45  48  50  62   44.333333  HDFC  HDFC

In [383]:
#df.groupby
grouped_grades = df.groupby("bank")
grouped_grades.mean()


A     B     C     D     E  target_var
bank                                          
HDFC  35.0  38.5  46.0  50.0  61.0   39.833333
SBI   15.0  16.0  17.0  20.5  23.0   16.000000

In [378]:
group_mean, group_std,group_max = grouped_grades.mean(),grouped_grades.std(),grouped_grades.max()
print(group_max)
print(group_std)
print(group_mean)

          A   B   C   D   E  target_var
hobby                                  
Biking   40  45  48  50  62   44.333333
Dancing  30  32  44  50  60   35.333333
                 A          B          C          D          E  target_var
hobby                                                                     
Biking   21.213203  24.041631  25.455844  24.041631  31.112698   23.570226
Dancing   7.071068   7.778175  15.556349  17.677670  22.627417   10.135197
            A     B     C     D     E  target_var
hobby                                            
Biking   25.0  28.0  30.0  33.0  40.0   27.666667
Dancing  25.0  26.5  33.0  37.5  44.0   28.166667


In [384]:
df.to_csv("my_df.csv")   #write to csv from py
my_df_loaded = pd.read_csv("my_df.csv", index_col=0) # read from csv to py
my_df_loaded

A   B   C   D   E  target_var hobby  bank
I    10  11  12  16  18   11.000000   SBI   SBI
II   20  21  22  25  28   21.000000   SBI   SBI
III  30  32  44  50  60   35.333333  HDFC  HDFC
IV   40  45  48  50  62   44.333333  HDFC  HDFC

In [123]:
try:
    df.to_excel("my_df.xlsx", sheet_name='df')
except ImportError as e:
    print(e)

In [124]:
city_loc = pd.DataFrame(
    [
        ["CA", "San Francisco", 37.781334, -122.416728],
        ["NY", "New York", 40.705649, -74.008344],
        ["FL", "Miami", 25.791100, -80.320733],
        ["OH", "Cleveland", 41.473508, -81.739791],
        ["UT", "Salt Lake City", 40.755851, -111.896657]
    ], columns=["state", "city", "lat", "lng"])
city_loc


state            city        lat         lng
0    CA   San Francisco  37.781334 -122.416728
1    NY        New York  40.705649  -74.008344
2    FL           Miami  25.791100  -80.320733
3    OH       Cleveland  41.473508  -81.739791
4    UT  Salt Lake City  40.755851 -111.896657

In [125]:
city_pop = pd.DataFrame(
    [
        [808976, "San Francisco", "California"],
        [8363710, "New York", "New-York"],
        [413201, "Miami", "Florida"],
        [2242193, "Houston", "Texas"]
    ], index=[3,4,5,6], columns=["population", "city", "state"])
city_pop

population           city       state
3      808976  San Francisco  California
4     8363710       New York    New-York
5      413201          Miami     Florida
6     2242193        Houston       Texas

In [126]:
pd.merge(left=city_pop, right=city_loc, on="city",how="inner")

population           city     state_x state_y        lat         lng
0      808976  San Francisco  California      CA  37.781334 -122.416728
1     8363710       New York    New-York      NY  40.705649  -74.008344
2      413201          Miami     Florida      FL  25.791100  -80.320733

In [128]:
pd.merge(left=city_pop, right=city_loc, on="city",how="outer")

population            city     state_x state_y        lat         lng
0    808976.0   San Francisco  California      CA  37.781334 -122.416728
1   8363710.0        New York    New-York      NY  40.705649  -74.008344
2    413201.0           Miami     Florida      FL  25.791100  -80.320733
3   2242193.0         Houston       Texas     NaN        NaN         NaN
4         NaN       Cleveland         NaN      OH  41.473508  -81.739791
5         NaN  Salt Lake City         NaN      UT  40.755851 -111.896657

In [331]:
pd.merge(left=city_pop, right=city_loc, on="city",how="right")

population            city     state_x state_y        lat         lng
0    808976.0   San Francisco  California      CA  37.781334 -122.416728
1   8363710.0        New York    New-York      NY  40.705649  -74.008344
2    413201.0           Miami     Florida      FL  25.791100  -80.320733
3         NaN       Cleveland         NaN      OH  41.473508  -81.739791
4         NaN  Salt Lake City         NaN      UT  40.755851 -111.896657

In [332]:
pd.merge(left=city_pop, right=city_loc, on="city",how="left")


population           city     state_x state_y        lat         lng
0      808976  San Francisco  California      CA  37.781334 -122.416728
1     8363710       New York    New-York      NY  40.705649  -74.008344
2      413201          Miami     Florida      FL  25.791100  -80.320733
3     2242193        Houston       Texas     NaN        NaN         NaN

In [129]:
city_pop2 = city_pop.copy()
city_pop2.columns = ["population", "name", "state"]
pd.merge(left=city_loc, right=city_pop2, left_on="city", right_on="name")

state_x           city        lat         lng  population           name  \
0      CA  San Francisco  37.781334 -122.416728      808976  San Francisco   
1      NY       New York  40.705649  -74.008344     8363710       New York   
2      FL          Miami  25.791100  -80.320733      413201          Miami   

      state_y  
0  California  
1    New-York  
2     Florida

In [335]:
result_concat= pd.concat([city_loc, city_pop])
result_concat

state            city        lat         lng  population
0          CA   San Francisco  37.781334 -122.416728         NaN
1          NY        New York  40.705649  -74.008344         NaN
2          FL           Miami  25.791100  -80.320733         NaN
3          OH       Cleveland  41.473508  -81.739791         NaN
4          UT  Salt Lake City  40.755851 -111.896657         NaN
3  California   San Francisco        NaN         NaN    808976.0
4    New-York        New York        NaN         NaN   8363710.0
5     Florida           Miami        NaN         NaN    413201.0
6       Texas         Houston        NaN         NaN   2242193.0

In [130]:
result_concat= pd.concat([city_loc, city_pop],axis=1)
result_concat

state            city        lat         lng  population           city  \
0    CA   San Francisco  37.781334 -122.416728         NaN            NaN   
1    NY        New York  40.705649  -74.008344         NaN            NaN   
2    FL           Miami  25.791100  -80.320733         NaN            NaN   
3    OH       Cleveland  41.473508  -81.739791    808976.0  San Francisco   
4    UT  Salt Lake City  40.755851 -111.896657   8363710.0       New York   
5   NaN             NaN        NaN         NaN    413201.0          Miami   
6   NaN             NaN        NaN         NaN   2242193.0        Houston   

        state  
0         NaN  
1         NaN  
2         NaN  
3  California  
4    New-York  
5     Florida  
6       Texas

In [131]:
result_concat.loc[3]

state                    OH
city              Cleveland
lat                 41.4735
lng                -81.7398
population           808976
city          San Francisco
state            California
Name: 3, dtype: object

In [135]:
city_eco = city_pop.copy()
city_eco["eco_code"] = [17, 17, 34, 20]
city_eco
city_eco["economy"] = city_eco["eco_code"].astype('category')
city_eco["economy"].cat.categories
#city_eco.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 3 to 6
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   population  4 non-null      int64   
 1   city        4 non-null      object  
 2   state       4 non-null      object  
 3   eco_code    4 non-null      int64   
 4   economy     4 non-null      category
dtypes: category(1), int64(2), object(2)
memory usage: 428.0+ bytes


In [348]:
city_eco["economy"].cat.categories = ["Finance", "Energy", "Tourism"]
city_eco

population           city       state  eco_code  economy
3      808976  San Francisco  California        17  Finance
4     8363710       New York    New-York        17  Finance
5      413201          Miami     Florida        34  Tourism
6     2242193        Houston       Texas        20   Energy

In [136]:
city_eco.sort_values(by="economy", ascending=False)

population           city       state  eco_code economy
5      413201          Miami     Florida        34      34
6     2242193        Houston       Texas        20      20
3      808976  San Francisco  California        17      17
4     8363710       New York    New-York        17      17

In [137]:
list(set(city_eco.economy))
list(city_eco['economy'].unique())

[17, 34, 20]

In [138]:
import numpy as np
df['name'] =np.repeat(np.array(["A","B"]), [2,2])
df


A   B   C   D   E   X  ysum  dec name
I    10  11  12  16  18  21   NaN  NaN    A
II   20  21  22  25  28  41   NaN  NaN    A
III  30  32  44  50  60  62   NaN  NaN    B
IV   40  45  48  50  62  85   NaN  NaN    B

In [141]:
df['name'].value_counts()

A    2
B    2
Name: name, dtype: int64