## Get current working directory and change directory

import os
import numpy as np

PATH = os.getcwd();      

print(PATH)    # Print the current working directory

os.chdir(PATH) # Change directory

#### 1-D

In [13]:
import os
import numpy as np
import math
import stat
import pandas as pd
#'/Users/apple/Desktop/'

In [4]:
os.getcwd()
os.chdir('/Users/apple/Desktop/Cares/RIMS/PY & R')

In [22]:
a = np.array([10, 1, 2, 3])
a
#a = pd.Series(a)
#print(a)
#df = pd.DataFrame(a)
#df.describe()

array([10,  1,  2,  3])

In [4]:
print (a)
print(a.shape)
print (type(a))

print (len(a))     # returns the size of the first dimension

[0 1 2 3]
(4,)
<class 'numpy.ndarray'>
4


#### 2-D, 3-D, ...:

In [5]:
a = np.array([[1.5, 2, 3], [4, 5, 6]])

print(a)
print(a.shape)
print(len(a))

[[1.5 2.  3. ]
 [4.  5.  6. ]]
(2, 3)
2


In [3]:
print (a)

print (type(a))

print (len(a))     # returns the size of the first dimension

a.shape

[0 1 2 3]
<class 'numpy.ndarray'>
4


(4,)

* __Evenly spaced__

In [4]:
np.arange(1,10,2)     # start, end (exlusive), step

print (a)

[0 1 2 3]


In [5]:
a = np.arange(10)        # 0 .. n-1  (!)

print (a)

[0 1 2 3 4 5 6 7 8 9]


* __By number of points__

In [9]:
a = np.linspace(0, 1, 6)   # start, end, num-points

print (a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [6]:
a = np.linspace(0, 1, 5, endpoint=False)

print (a)

[0.  0.2 0.4 0.6 0.8]


* __Common arrays__

In [7]:
a = np.ones((3, 3),dtype=int)  # reminder: (3, 3) is a tuple

print (a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
a = np.zeros((2, 2))

print (a)

[[0. 0.]
 [0. 0.]]


In [9]:
a = np.eye(3)

print (a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
b = np.array([1, 2, 3, 4])
print(b)
a = np.diag(b)
print (a)

[1 2 3 4]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
a = np.random.rand(4)
print(a)
print("\n")
b = np.random.rand(4,3)  
print(b)

[0.77729134 0.04167889 0.27391808 0.31484445]


[[0.96770633 0.72836277 0.15603437]
 [0.51561943 0.60375401 0.18280597]
 [0.07385734 0.63337842 0.94208717]
 [0.27930414 0.13777072 0.41595867]]


In [39]:
import numpy as np
# The * operator on the list replicates the items in a list, n number of times given list * n 

example_list_one = [1, 2, 3, 4] * 1000

example_list_two = [4, 3, 2, 1] * 1000

# We'll look at the code given here later, but for now understand that numpy arrays can be created from python lists

example_array_one = np.array(example_list_one)

example_array_two = np.array(example_list_two)
example_list_one

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,


In [41]:
print(type(example_list_one))
print(type(example_array_one))

<class 'list'>
<class 'numpy.ndarray'>


In [42]:
print(len(example_list_one))
print(example_array_one.shape)

4000
(4000,)


In [11]:
def vector_addition(vector_one, vector_two):
    
    new_vec = []
    
    for i in range(len(vector_one)):
        
        new_vec.append(vector_one[i] + vector_two[i])
        
    return new_vec

In [44]:
%%timeit
vector_addition(example_list_one,example_list_two)

753 µs ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [45]:
%%timeit
example_array_one + example_array_two

3.28 µs ± 257 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
x = np.array([1, 2])      # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int32)  # Force a particular datatype

print (x.dtype, y.dtype, z.dtype)

int64 float64 int32


In [5]:
numpy_one_dim = np.array([1, 2, 3, 4, 5, 6])

print(numpy_one_dim)

print(numpy_one_dim.shape)

[1 2 3 4 5 6]
(6,)


#### Two Dimensional Array

    Shape : (nrows, ncols)

In [6]:
numpy_two_dim = np.array([
                            [1, 2, 3, 4, 5, 6],
                            [11, 22, 33, 44, 55, 66]
                         ])

print(numpy_two_dim)

print(numpy_two_dim.shape)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]
(2, 6)


In [47]:
numpy_three_dim = np.array([
                            [
                                [1, 2, 3, 4, 5, 6],
                                [11, 22, 33, 44, 55, 66],
                                [111, 222, 333, 444, 555, 666]
                            ],
                            [
                                [21, 22, 23, 24, 25, 26],
                                [221, 222, 233, 244, 255, 266],
                                [2211, 2222, 2333, 2444, 2555, 2666]
                            ]
                         ])


print(numpy_three_dim)

print(numpy_three_dim.ndim)

print(numpy_three_dim.shape)

[[[   1    2    3    4    5    6]
  [  11   22   33   44   55   66]
  [ 111  222  333  444  555  666]]

 [[  21   22   23   24   25   26]
  [ 221  222  233  244  255  266]
  [2211 2222 2333 2444 2555 2666]]]
3
(2, 3, 6)


##### Activity

    What is the shape of the following array?

In [13]:
 dim4 = np.array ( [
       [
           [
               [
                   25, 23, 23, 222, 441
               ],
               
               [
                   25, 23, 23, 222, 441
               ],
               
               [
                   25, 23, 23, 222, 441
               ]
           ],
           
           [
               [
                   25, 23, 23, 222, 441
               ],
               
               [
                   25, 23, 23, 222, 441
               ],
               
               [
                   25, 23, 23, 222, 441
               ]
           ]
       ]
   ])
print(dim4.ndim)
print(dim4.shape)

4
(1, 2, 3, 5)


In [56]:
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [9]:
# numpy.reshape - Gives a new shape to an array without changing its data
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [59]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [10]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


## Indexing, Slicing and Iterating

In [16]:
a = np.arange(12)
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
a[2::2]  # starting from n and skip n

array([ 2,  4,  6,  8, 10])

In [17]:
print(a[2:5])

[2 3 4]


In [18]:
print(a[:3])

[0 1 2]


In [53]:
print (a[2])
print (a[2:5])
print(a[:3])

2
[2 3 4]
[0 1 2]


In [19]:
print (a[:])
print (a[0:10])
print (a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [26]:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


__Multidimensional__ arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [27]:
a = np.array([
                [0, 1, 2, 3, 4, 5],
                [10, 11, 12, 13, 14, 15],
                [20, 21, 22, 23, 24, 25],
                [30, 31, 32, 33, 34, 35],
                [40, 41, 42, 43, 44, 45],
                [50, 51, 52, 53, 54, 55]
            ])
print (a)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [35]:
print(a[1:5,1:4])    

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [37]:
print(a[-5])

[10 11 12 13 14 15]


__Iterating__ over multidimensional arrays is done with respect to the first axis:

In [42]:

    
for row in a[:2,:4]:
    print(row)

[0 1 2 3]
[10 11 12 13]


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [45]:
for row in a[:3,:3].flat:
    print(row)

0
1
2
10
11
12
20
21
22


##### ACTIVITY:
Create a 3X4 array as follows:


In [52]:
ar=np.array(
    [[4,6,7,8],
    [9,6,1,2],
    [10,11,2,3]
            ])
print(ar)
print(ar.shape)
print(ar.reshape(4,3))

[[ 4  6  7  8]
 [ 9  6  1  2]
 [10 11  2  3]]
(3, 4)
[[ 4  6  7]
 [ 8  9  6]
 [ 1  2 10]
 [11  2  3]]


## Reshaping numpy arrays


In [67]:
numpy_two_dim = np.array([ [2, 3, 4, 5, 6], [22, 33, 44, 55, 66] ] )
numpy_two_dim

array([[ 2,  3,  4,  5,  6],
       [22, 33, 44, 55, 66]])

#### Transpose

In [39]:
numpy_three_dim = np.array([[[ 1, 2, 3, 4, 5, 6],
        [  11,   22,   33,   44,   55,   66],
        [ 111,  222,  333,  444,  555,  666]],

       [[  21,   22,   23,   24,   25,   26],
        [ 221,  222,  233,  244,  255,  266],
        [2211, 2222, 2333, 2444, 2555, 2666]]])

print(numpy_three_dim)
print(numpy_three_dim.shape)

[[[   1    2    3    4    5    6]
  [  11   22   33   44   55   66]
  [ 111  222  333  444  555  666]]

 [[  21   22   23   24   25   26]
  [ 221  222  233  244  255  266]
  [2211 2222 2333 2444 2555 2666]]]
(2, 3, 6)


In [40]:
numpy_three_dim.shape

(2, 3, 6)

Let's reshape numpy_three_dim to (9, 4) using __reshape__

In [41]:
numpy_three_dim.reshape(9, 4)

array([[   1,    2,    3,    4],
       [   5,    6,   11,   22],
       [  33,   44,   55,   66],
       [ 111,  222,  333,  444],
       [ 555,  666,   21,   22],
       [  23,   24,   25,   26],
       [ 221,  222,  233,  244],
       [ 255,  266, 2211, 2222],
       [2333, 2444, 2555, 2666]])

If you dont know about the size of one dimesion, you can use __-1__ to tell numpy to figure it out

In [42]:
numpy_three_dim.reshape(9, -1)

array([[   1,    2,    3,    4],
       [   5,    6,   11,   22],
       [  33,   44,   55,   66],
       [ 111,  222,  333,  444],
       [ 555,  666,   21,   22],
       [  23,   24,   25,   26],
       [ 221,  222,  233,  244],
       [ 255,  266, 2211, 2222],
       [2333, 2444, 2555, 2666]])

The __flatten__ method helps us get to a one dimensional numpy array

In [43]:
numpy_three_dim.flatten()

array([   1,    2,    3,    4,    5,    6,   11,   22,   33,   44,   55,
         66,  111,  222,  333,  444,  555,  666,   21,   22,   23,   24,
         25,   26,  221,  222,  233,  244,  255,  266, 2211, 2222, 2333,
       2444, 2555, 2666])

In [ ]:
numpy_three_dim.flatten().shape

### Row array vs Column array

A one dimensional numpy array has only one number in it's shape so therefore it is neither a row vector, not a column vector

In [44]:
numpy_one_dim = np.array([1,2,3,4,5,6])
print(numpy_one_dim)
print(numpy_one_dim.shape)

[1 2 3 4 5 6]
(6,)


To explicitly make it a row vector / array

In [45]:
numpy_one_dim.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

To explicitly make it a column vector / array

In [46]:
numpy_one_dim.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

We can also use -1 if we do not know the number of elements in the array to create a column vector`

In [47]:
numpy_one_dim.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## Broadcasting

#### Understanding Vectorized Operations in numpy through the demonstration of Min-Max scaling

In [53]:
# Create a numpy array that starts at 0 and end at 99

A = np.arange(100)

print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [56]:
Amax, Amin, Amean, Astd = A.max(), A.min(), A.mean(), A.std()

print(Amax, Amin, Amean, Astd)

99 0 49.5 28.86607004772212


In [60]:
Ascaled = (A - Amin)/(Amax - Amin)

print(Ascaled)

Zscore = (A - Amean)/Astd
print(Zscore)
import pandas as pd
pd.Series(Ascaled,Zscore)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

-1.714816    0.000000
-1.680173    0.010101
-1.645531    0.020202
-1.610888    0.030303
-1.576245    0.040404
               ...   
 1.576245    0.959596
 1.610888    0.969697
 1.645531    0.979798
 1.680173    0.989899
 1.714816    1.000000
Length: 100, dtype: float64

#### NumPy - Arithmetic Operations

In [61]:
print ('First array:') 
a = np.arange(9).reshape(3,3) 
print (a) 

print ('Second array:') 
b = np.array([10,10,10]) 
print (b) 

print ('Add the two arrays:')
print (np.add(a,b))
print (a+b)

print ('Subtract the two arrays:')
print (np.subtract(a,b)) 
print (a-b)

print ('Multiply the two arrays:')
print (np.multiply(a,b)) 
print (a*b)

print ('Divide the two arrays:')
print (np.divide(a,b))
print (a/b)

print ('Matrix Multiplication:')
print (np.matmul(a,b)) 

First array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Second array:
[10 10 10]
Add the two arrays:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Subtract the two arrays:
[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]
[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]
Multiply the two arrays:
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]
Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
Matrix Multiplication:
[ 30 120 210]
